### ISSUE TITLE
Error on audio stop

### ISSUE THREAD

**Issue by leonardogruppelli** [Aminerman/vue-kinesis#21]
There's an error ocurring when changing the state of the `playAudio` **prop** from `true` to `false`. As I see, the problem is that the wrong function is being called on the audio ref, instead of    `this.audioRef.stop()` it should be `this.audioRef.pause()`.

**Comment by Aminerman** [comment]
You're correct! I fixed it. Just get the latest package version and it should be all fine. Let me know if your problem is fixed. Thank you :)

**Comment by leonardogruppelli** [comment]
It's fixed! Thanks!
And awesome lib btw, congratulations man!

**Comment by Aminerman** [comment]
Thank you! Let me know if you find something else or if you think about a specific features. I still have a lot of ideas for this project.
