### ISSUE TITLE
A way to detect in view port

### ISSUE THREAD

**Issue by nam-co** [Aminerman/vue-kinesis#24]
Hi, thanks for the package, maybe it could be cool to activate for example a clip-path animation when element on viewport and combined with mouse parallax, is there a way to do this in kinesis?

Thank you for your time

**Comment by Aminerman** [comment]
Hello,
Just to make sure that I understand your issue, do you just want a way to know if the element is in the viewport? Or is your question about if Kinesis can animate clip-path property?

**Comment by nam-co** [comment]
Hi Aminerman, thanks for your prompt reply, is not really a issue, but more an idea, iis it possible to detect when element is in viewport and then for example add/remove a xx class

but your second question could be visually cool, can Kinesis animate clip-path property? or for example css @keyframe based on screen scroll percentage

**Comment by Aminerman** [comment]
For now there is no way to animate other than transforms. There will be definitely at some point more possibilities. 

The **Keyframe** idea is something than I might try to implement soon.

For the **viewport** thing, what about just using a package like [this one](https://www.npmjs.com/package/vue-in-viewport-directive)?
