### ISSUE TITLE
Parallax breaks OwlCarousel slider swipe

### ISSUE THREAD

**Issue by ErriourRU** [Aminerman/vue-kinesis#25]
I have [vue OwlCarousel package](https://www.npmjs.com/package/vue-owl-carousel2). If I'm trying set parallax on slide, slide becomes impossible to swipe.
Example (common behavior of OwlCarousel at top and behavior with `<kinesis-container>` below):

![bandicam 2020-03-03 22-08-15-887](https://user-images.githubusercontent.com/43105218/75774554-f205c580-5d9b-11ea-8802-b581f4f668fd.gif)

**Comment by Aminerman** [comment]
Could you make a small CodeSandbox that reproduces this behavior? It would be quite helpful.

**Comment by Aminerman** [comment]
I reproduced the bug and updated the package with a fix. Please give it a try and tell me if it fixes your bug.
Thanks for your feedback!

**Comment by ErriourRU** [comment]
Yep, no problems now. Thanks!
