### ISSUE TITLE
Scroll and Mouse movement

### ISSUE THREAD

**Issue by Scaalees** [Aminerman/vue-kinesis#28]
Loving this package, so easy to use and perfect for what I need (been trying to move away from scroll magic for simple bits).

I've just got a question, is it possible for a container to interact on scroll and mouse movement.

For example, having an image scale on scroll but the mouse controlling the translation relative to the mouse.

Thanks in advance

**Comment by Aminerman** [comment]
Hello! Thanks a lot for your words! I'm glad that you like it and find it easy to use.
It depends on what your use case is, but I made a `codesandbox` that might help: 
https://codesandbox.io/s/laughing-panini-0veys
I'm using a `kinesis-scroll` inside a `kinesis-element`. Basically, kinesis-scroll is a component that doesn't depend on a container. 
Let me know if it helps and if it's still optimal for what you want to achieve. If not I will try to think of a solution.

**Comment by Scaalees** [comment]
Perfect thank you for that, I'll give it ago.

**Comment by Aminerman** [comment]
Great!
Yes, I'll do so. I'm working on improving the doc and the demo page.
