### ISSUE TITLE
When you move cursor outside the browser window, the kinesis elements briefly jump forward and back (see video)

### ISSUE THREAD

**Issue by dominik-wbz** [Aminerman/vue-kinesis#42]
Can someone explain this behavior and how to fix it?

https://youtu.be/Q-ZENarErG0

**Comment by david-noe** [comment]
I have the same issue. Is there a way to fix it?

**Comment by dominik-wbz** [comment]
No luck so far. Will continue to work on this project in few weeks. Will keep this thread updated if I find anything.

**Comment by Aminerman** [comment]
Hello guys, @dominik-wbz & @david-noe 
I haven't worked on this project due to some personal issues. My apologies. I'll be looking at the issue and how to fix it soon. On my demo page I don't have this issue. So I might ask if you can reproduce an example if I don't succeed on finding the reason.

**Comment by david-noe** [comment]
Hi @Aminerman, thanks for your reply. I am currently working on this page: https://david-mzee-1.vercel.app/
When moving the cursor outside the Kinesis Div. (e.g. in the navigation bar) the animation jumps.

**Comment by Aminerman** [comment]
@david-noe Indeed, I actually just noticed that the issue started to appear since 1.1.4 version. So that gives me a clue. Can you confirm that 1.1.3 works fine?

**Comment by david-noe** [comment]
Yes :) version 1.13 works fine.

**Comment by dominik-wbz** [comment]
Hi @Aminerman thanks for taking the time for this. I downgraded the version to 1.13 and can also confirm that the problem is gone 🤷‍♂️

**Comment by Aminerman** [comment]
Hello guys! @dominik-wbz & @david-noe  Thanks for your feedback.
Can you please test version `1.1.7` ? It should be fine now. 
I'll be working on solving the other issues and add new features soon. If you have any suggestions or ideas do not hesitate.

**Comment by david-noe** [comment]
Thanks you so much! Now it works fine :)
