### ISSUE TITLE
No Typescript support

### ISSUE THREAD

**Issue by mathewcst** [Aminerman/vue-kinesis#46]
I'm trying to use this lib within my app but, since I'm using Typescript, I can't because it doesn't have a type declaration

`Could not find a declaration file for module 'vue-kinesis'. '/node_modules/vue-kinesis/dist/vue-kinesis.umd.js' implicitly has an 'any' type.`

**Comment by Aminerman** [comment]
Thanks for pointing that out. What is your suggestion?

**Comment by Aminerman** [comment]
I'll close this issue for now, do not hesitate to reopen it when you have a suggestion or want to help with this. 
In the meanwhile, you could maybe use this to help you : 
https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam
