### ISSUE TITLE
Vue3 Compatibility

### ISSUE THREAD

**Issue by MadeInFck** [Aminerman/vue-kinesis#49]
Hi, are you planning to migrate your module to Vue 3?

**Comment by Aminerman** [comment]
Hello! Yes, it's in the plans. But it's not the top priority now. I'm working on a lot of new features and a new demo and documentation page. If there are compatibility issues though. I might make it a priority. 
So let me know if you have had issues with it please.

**Comment by eybarta** [comment]
Hey man, thx for amazing work...
trying to import your library into a vue3/vite project,
getting this error:
**Failed to resolve module import "vue-kinesis/dist/vue-kinesis.esm.js". (imported by /src/main.js)**

I tried to build your project inside the folder with _npm run build:es_, but got errors,
Do you have any idea how to resolve this?

Thank you

**Comment by Aminerman** [comment]
I'll try to reproduce it and get back to you with an answer.

**Comment by Aminerman** [comment]
Hi again, I did manage to reproduce the issue and investigate for a while. My conclusion is that there are indeed few compatibility issues that I'll have to figure out and fix.

**Comment by Aminerman** [comment]
Hello once again,
I've actually managed to make it compatible with Vue3 on a Vite project. I just need to add few tweaks here and there before relasing. So expect a release later today or tomorrow at most. I'll let you know then.

**Comment by eybarta** [comment]
You rock! that's great news! 

thanks for the fast response.

**Comment by MadeInFck** [comment]
Amazing, thanks for managing that migration so fast. Can't wait it to use it for my next projet!

**Comment by Aminerman** [comment]
Hello guys,
You can now use vue-kinesis in a Vue3 project by doing :  `npm install vue-kinesis@next` 
It will install the version 2.0.1
So now the branch `next` is the branch for the Vue3 compatible version.
Please let me know if it works for you and if you encounter any other issues :)

**Comment by eybarta** [comment]
Works perfectly for me, thank you very much!

**Comment by Aminerman** [comment]
Perfect :) I updated the README accordingly.
I'll close the issue now. If there is anything that doesn't work as expected, you can open another one.
Have fun with the library :)
