### ISSUE TITLE
Noob problem with modules

### ISSUE THREAD

**Issue by macizomedia** [Aminerman/vue-kinesis#53]
Hi my setup is with vue2, don't know if I am missing some Extra config as I am getting this warning and the element does not show on screen. 

Thanks if I can have a Hint!

```
warning  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

"export 'createBlock' was not found in 'vue'

 warning  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

"export 'createCommentVNode' was not found in 'vue'

 warning  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

"export 'createVNode' was not found in 'vue'

 warning  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

"export 'openBlock' was not found in 'vue'

 warning  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

"export 'renderSlot' was not found in 'vue'

 warning  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

"export 'resolveDynamicComponent' was not found in 'vue'

 warning  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

"export 'withCtx' was not found in 'vue'
```

**Comment by Aminerman** [comment]
Hello! Well there is no such thing as a noob question. Many things can be understandably a little obscure.
Well I actually tried to create a new Vue2 project where I imported vue-kinesis.esm and I got none of these warnings, and the components work fine.
Are you sure you installed the Vue2 version of `vue-kinesis`? In your `package.json`, you should see the `1.2.3` version. 

If it still doesn't work, can you please push a repository so I can see your code? Just create a new Vue2 project, and install vue-kinesis in it, please.

**Comment by macizomedia** [comment]
Thanks for quick replay at the moment I am rebuilding the project. I might have an polluted node_modules folder. Will let you know how it goes. Thanks!

**Comment by Aminerman** [comment]
Hello! I'll close this issue for now. If you still have problems and would require more investigation, you can reopen it :)
