### ISSUE TITLE
Active Prop on container not working

### ISSUE THREAD

**Issue by michaelilic** [Aminerman/vue-kinesis#71]
I saw that setting active is not working as expected and described in the documentation. Is there a reason for that?

The if loop for checking if active is set in the container prop seems to be commented out.

`methods: {    
// eslint-disable-next-line func-names    
handleMovement: throttle(function (event) {     
 // if (!this.active) return;
`

**Comment by Aminerman** [comment]
@michaelilic 
I released a new version, `1.3.2` and `2.0.5` (for Vue3) with the fix for this

**Comment by michaelilic** [comment]
Thanks. It seems like this has introduced a new error. After updating to the latest version i get this error:

`client.js?1b93:196 ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js 231:22Module parse failed: Unexpected token (231:22)You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders|   data() {|     return {>       shape: this.$el?.getBoundingClientRect(),|       isMoving: false,|       leftOnce: false,`
