### ISSUE TITLE
Error when attempting to build project

### ISSUE THREAD

**Issue by DuelMonster** [Aminerman/vue-kinesis#72]
error  in ./node_modules/vue-kinesis/dist/vue-kinesis.esm.js

Module parse failed: Unexpected token (231:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   data() {
|     return {
>       shape: this.$el?.getBoundingClientRect(),
|       isMoving: false,
|       leftOnce: false,

**Comment by Aminerman** [comment]
What version of Vue and Kinesis are you using?

**Comment by DuelMonster** [comment]
Sorry, Vue 2 and Kinesis 1.3.2

**Comment by Aminerman** [comment]
@DuelMonster 
Indeed, 1.3.2 had this issue. Rollup completely ignored Optional Chaining when building.
I fixed it in 1.3.3 just now, and I tested it. Let me know if it works for you.

**Comment by DuelMonster** [comment]
That's fixed it. Thanks for the swift turnaround 🥰
