### ISSUE TITLE
Allow kinesis-element in both sides of the movement like x axis and y axis

### ISSUE THREAD

**Issue by dt2036** [Aminerman/vue-kinesis#73]
Hello @Aminerman 
Is there any solution for both sides of the movement like x axis and y axis in kinesis-element?

      <kinesis-element :strength="10"  axis="y">
        <img loading="lazy" src="https://homepages.cae.wisc.edu/~ece533/images/airplane.png"
	width="300" height="200" alt="Radixweb for Custom Software Development" > 
      </kinesis-element>      

Thanks in advance.

**Comment by Aminerman** [comment]
I'm not sure I understand correctly. You mean you would like to restrict the movement for both axis at the same time?

**Comment by Aminerman** [comment]
@dt2036 I'm not sure I understand correctly. You mean you would like to restrict the movement for both axis at the same time?

**Comment by dt2036** [comment]
> @dt2036 I'm not sure I understand correctly. You mean you would like to restrict the movement for both axis at the same time?

No, I want transition movement left to right and top to bottom vice versa.

**Comment by dt2036** [comment]
[demo.txt](https://github.com/Aminerman/vue-kinesis/files/6668775/demo.txt)
check-in this code pan https://codesandbox.io/s/vue-kinesis-6x3kd app.vue file in replacing the above demo.txt file.

**Comment by dt2036** [comment]
@Aminerman Thanks. my issue is solved. removed axis="y" from my code and my goal is achieved.

**Comment by Aminerman** [comment]
Oh I get it now.

Yes, the axis prop is only when you want to restrict the movement. You don't need to specify it if you want a free movement.
