### ISSUE TITLE
Unsupportable for Vue3

### ISSUE THREAD

**Issue by vikash2806** [Aminerman/vue-kinesis#85]
**Is your feature request related to a problem? Please describe.**
Iam not able to use vue-kinesis in Vue3

**Comment by Aminerman** [comment]
Did you install the @next version?
`npm install --save vue-kinesis@next`
If so, please give further explanations about your issue.

**Comment by vikash2806** [comment]
https://codesandbox.io/s/silent-haze-emyps

**Comment by Aminerman** [comment]
Hi again,
I juste created this project to test: 
https://github.com/Aminerman/vue3-kinesis-test

I just installed vue-kinesis@next, added it in the main.js, and used the components in App.vue
So everything works fine.

You can either take inspiration from this, or share your code so I can help you debugging this issue.

**Comment by vikash2806** [comment]
Hey, thank you for the repository. I will try to solve the problem in my code with the help of your repository.
I will let you know if  I am still facing the issue.

**Comment by Aminerman** [comment]
I'll consider this issue resolved. You can reopen it if it's not.
