### ISSUE TITLE
i have vue: "^2.6.14" and  vue-kinesis: "^1.3.3" still the same error

### ISSUE THREAD

**Issue by sunilregmi777** [Aminerman/vue-kinesis#89]
![Screenshot_3](https://user-images.githubusercontent.com/33472421/154063569-659d029c-4d35-4569-8125-ca122a0990e9.png)

**Comment by Aminerman** [comment]
https://codesandbox.io/s/festive-bush-1khjnx

It doesn't seem to cause any issue.
