### ISSUE TITLE
compiling problem npm version

### ISSUE THREAD

**Issue by joudy-almahjoub** [Aminerman/vue-kinesis#93]
I install it as a npm package but  why when it comes to compiling it's not working and my project stop compile.?

**Comment by Aminerman** [comment]
How would I know if you're not giving any further detail? There is a bug issue template that you could've followed.
Can you provide a public repository that reproduces this issue? Thanks.

**Comment by joudy-almahjoub** [comment]
sorry for not giving you Specified details.
that's my code:
`<template>
<div >
<kinesis-container :duration="1000" :easing="easing">

    <kinesis-element : strength="-5" :type="'translate'">
`<v-img src="../assets/splash.png"  id="My-img"></v-img>`

     </kinesis-element>

</kinesis-container>
</div>
</template>`
I followed the installation steps, as i type "npm run build" the project stop building.

**Comment by Aminerman** [comment]
Thank you for providing some details.
If you can show me the error you have when you run `npm run serve`, that would help.
My guess is that you didn't use `kinesis-container`
You can find examples here : https://aminerman.com/kinesis/#/
Or here : https://codesandbox.io/s/emyps?file=/src/components/HelloWorld.vue
